### ISSUE TITLE
V-net 3d

### ISSUE THREAD

**Issue by houDaelo** [shalabh147/Brain-Tumor-Segmentation-and-Survival-Prediction-using-Deep-Neural-Networks#2]
Can you tell me  how you train V-net 3D ? Thank you

**Comment by shalabh147** [comment]
@houDaelo you can have a look at our project [report](https://www.cse.iitb.ac.in/~shalabhgupta/Report.pdf) where we clearly mention the hyper parameters and optimizer for VNet training and the training code template for 3D Vnet is exactly same as the training code for 3D Unet (inside 3D Unet folder). Kindly have a look. Thanks!

**Comment by houDaelo** [comment]
thank you so mush ,  this was very helpful for my final project but  i do
the same think but i have a small problem which is the dice coefficient
only reach 0.24  that's why i have  a bad prediction  can you just explain
for me
you loop for 180 patient and in each step you train the model for one
patient and save the model  and repeat the same thing for 60 eposh?
