### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by KanchanRani** [shalabh147/Brain-Tumor-Segmentation-and-Survival-Prediction-using-Deep-Neural-Networks#3]
Hi
Thanks in Advance
when i try to Run the -> Brain-Tumor-Segmentation-and-Survival-Prediction-using-Deep-Neural-Networks/2D_2class_models/2D_axis1/2d_axis1.ipynb file in Jupyternotebook   it gives the following error.
please resolve this issue.

![Capture](https://user-images.githubusercontent.com/76881286/103484369-55291400-4e14-11eb-85f0-2d7c24b2b0c7.PNG)
![Capture1](https://user-images.githubusercontent.com/76881286/103484393-8b669380-4e14-11eb-879f-6687541e68e6.PNG)

**Comment by shalabh147** [comment]
Can you please try printing class weights before line 295 and show me the output?

**Comment by KanchanRani** [comment]
![Capture3](https://user-images.githubusercontent.com/76881286/103484842-d03ff980-4e17-11eb-9aea-e16607d84691.PNG)

**Comment by shalabh147** [comment]
Okay, data loading looks correct to me. Can you please remove the last argument class_weight in model.fit function and run the script? class weights is supposed to tackle class imbalance problem, but there seems some problem with that so maybe you can try training without that argument.

**Comment by KanchanRani** [comment]
Now, It is executing smoothly. I have two doubts:-
1) Have you trained this model on all HGG Patient scans for all slices?
2) Model. save is written two times at line 303 and 346. why it is so?
Thank you.

**Comment by shalabh147** [comment]
> 1. Have you trained this model on all HGG Patient scans for all slices?

No, we have trained only on first 180 patient scans, as can be seen in the looping range. Also only those 2D slices have been used for training which contain both tumor and non-tumor regions, to prevent bias in the model.

> 2. Model. save is written two times at line 303 and 346. why it is so?

No special reason, the first model.save saves the model after every epoch of training. This is a good practice usually since there may occur instances of interruption while training the model. So to avoid training from scratch, we save the model after every epoch. Model.save in the end is kind of redundant and not really needed.

**Comment by shalabh147** [comment]
> > 1. Have you trained this model on all HGG Patient scans for all slices?
> >    No, we have trained only on first 180 patient scans, as can be seen in the looping range. Also only those 2D slices have been used for training which contain both tumor and non-tumor regions, to prevent bias in the model.
> 
> > 1. Model. save is written two times at line 303 and 346. why it is so?
> >    No special reason, the first model.save saves the model after every epoch of training. This is a good practice usually since there may occur instances of interruption while training the model. So to avoid training from scratch, we save the model after every epoch. Model.save in the end is kind of redundant and not really needed.

**Comment by KanchanRani** [comment]
Thank you for clearing my all doubts!!!

**Comment by KanchanRani** [comment]
Hi
when i try to execute 2d_axis1_results_2class.ipynb
it gives following error
![0](https://user-images.githubusercontent.com/76881286/103520125-b0064e00-4e9c-11eb-916b-816a96e4a925.PNG)
![1](https://user-images.githubusercontent.com/76881286/103520129-b268a800-4e9c-11eb-8b66-77365fcc424b.PNG)
![2](https://user-images.githubusercontent.com/76881286/103520132-b4326b80-4e9c-11eb-830a-639556d5f62d.PNG)
![3](https://user-images.githubusercontent.com/76881286/103520135-b5639880-4e9c-11eb-837e-2208d386bda3.PNG)
![4](https://user-images.githubusercontent.com/76881286/103520139-b694c580-4e9c-11eb-92e9-749f6bc8948e.PNG)
Kindly resolve this issue.
